players-choose-mode:
  file: "players.json"
  save-on-change: false
  coreprotect-log: true
  disable-cooldown: 300
  excluded-worlds:
    - world_nether
    - world_the_end
  messages:
    no-player: "§cPlayer §e{player} §cdoesn't exist or isn't connected."
    disabled-world: "§cSelecting a PvP mode is forbidden in this world."
    already-mode: "§cPlayer §e{player} §cis already in mode §e{mode}§c."
    cant-disable: "§cYou still have to wait §e{time} §cminutes before disabling PvP."
    display-mode: "§bYou PvP mode is currently §e{mode}§b."
    changed-mode: "§aThe PvP mode of §e{player} §ais now §e{mode}§a."
    bypass-a-disabled-player: "§eWarning ! This player disabled PvP."