main: fr.bidulman.fightregulator.FightRegulator
name: FightRegulator
author: Bidulman
version: 1.0
api-version: 1.20
softdepend:
  - CoreProtect
description: Offers you more settings about PvP in your server
commands:
  fight-regulator:
    description: Main command of the plugin
    aliases:
      - pvp
    usage: /fight-regulator [on/off] [player]
    permission: fight-regulator.use
permissions:
  fight-regulator.use:
    description: Allows you to use the main command of the plugin
    default: false
  fight-regulator.change:
    description: Allows you to change your PvP mode
    default: false
  fight-regulator.change-others:
    description: Allows you to change others PvP mode
    default: op
  fight-regulator.bypass:
    description: Allows you to hit other players even if it is forbidden
    default: op
